# Sensor Data Sparsity Test
# Use only 1/4 of LiDAR points (every 4th measurement)

experiment:
  name: "sparse_4"
  description: "Test with sparse sensor data: use 1/4 of LiDAR points (90 instead of 360)"

data:
  sensor_log: "data/sensor_data_clean.csv"

robot:
  initial_pose: [0.0, 0.0, 0.0]  # Correct initial pose

sensors:
  lidar:
    device_name: "LDS-01"
    noise_std: 0.02            # Baseline noise
    max_range: 3.5
    sparsity: 4                # Use every 4th point (360/4 = 90 points)

  odometry:
    alphas: [0.1, 0.1, 0.1, 0.1]  # Baseline noise

random_seed: 42
output_dir: "results"
