# Noise Level: 50% increased sensor noise

experiment:
  name: "noise_50"
  description: "50% increased sensor noise over baseline"

data:
  sensor_log: "data/sensor_data_clean.csv"

robot:
  initial_pose: [0.0, 0.0, 0.0]

sensors:
  lidar:
    device_name: "LDS-01"
    noise_std: 0.030           # 50% increase: 0.02 * 1.5 = 0.030
    max_range: 3.5
    sparsity: 1

  odometry:
    alphas: [0.15, 0.15, 0.15, 0.15]  # 50% increase

random_seed: 42
output_dir: "results"
