# Data Collection Configuration
# Used by data_logger controller to collect sensor data

collection:
  trajectory: "../../maps/traj/traj_eval_complex.csv"  # or traj_debug_square.csv
  output_file: "sensor_data_clean.csv"
  output_dir: "../../data"
  log_dt: 0.02  # 20ms logging interval

robot:
  def_name: "TB3"
  fallback_name: "TurtleBot3Burger"
  wheel_base: 0.160
  wheel_radius: 0.033

sensors:
  lidar:
    device_name: "LDS-01"

# Note: This collects CLEAN data (no noise)
# Noise is added offline using noise_models.py
